repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.0.291
    hooks:
      - id: ruff
        args:
          - --select=B,I,RUF,UP  # Run specific checks
          - --extend-select=E  # Ensure default checks are included
          - --fix  # Automatically fix issues

