name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Formatting Job
  format:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]  # Minimum and maximum Python versions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
           python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install pre-commit
      - name: Install the package
        run: python -m pip install .[dev]
      - name: Run pre-commit
        run: pre-commit run --all-files
      - name: Show formatting diff on failure
        if: failure()
        run: git diff  # Show the formatting changes needed

  # Tests Job
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, 3.13]  # Minimum and maximum Python versions
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the package
        run: python -m pip install .[dev]
      - name: Install dependencies
        run: |
          python -m venv venv
          . venv/bin/activate
          pip install .[tests]
      - name: Run tests
        run: |
          . venv/bin/activate
          nox -s tests  # Running tests using nox

